### ISSUE TITLE
XMLHttpRequest Error

### ISSUE THREAD

**Issue by allemoura** [bienvenuelisis/google_maps_directions#1]
Hi, getDirections on flutter web creates XMLHttpRequest Error.

**Comment by bienvenuelisis** [comment]
Can you submit the trace of the Error ?

UPDATE : As I analyze, this error is not due to the package. 

It is a common problem when debugging your flutter web application in development mode.

Try the steps described in this StackOverflow answer to resolve the error : https://stackoverflow.com/a/68786561/10256884.

**Comment by bienvenuelisis** [comment]
Feel free to reopen the issue, if the previous answer didn't address your issue.
